apiVersion: v1
kind: ConfigMap
metadata:
  name: regulator-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: aa2fbaff-98da-471c-9a67-19029781eddf
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: regulator-postgres-storage-volume
  labels:
    name: regulator-postgres-storage-volume
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage
    path: /projects/regulator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regulator-postgres-storage-claim
  labels:
    app: regulator-postgres
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: regulator-postgres-storage-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regulator-postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regulator-postgres-server
  template:
    metadata:
      labels:
        app: regulator-postgres-server
    spec:
      containers:
        - name: regulator-postgres-server
          image: postgres:12.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: regulator-postgres-config
          env:
            - name: PGDATA
              value: '/mnt/my-nfs/pg_data'
          volumeMounts:
            - mountPath: /mnt/my-nfs
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: regulator-postgres-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: regulator-postgres-server
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: regulator-postgres-server
